### ISSUE TITLE
Feed structure has changed

### ISSUE THREAD

**Issue by jeremycherfas** [jeremycherfas/pesos-instagram-to-withknown#3]
Feed structure from Instagram appears to have changed to that the caption display now contains things it shouldn't, like the `src` of the image and `alt` text. 

Line 66 is almost certainly where the problem lies. It uses a very crude `substr` to extract the bit it wants. Rethink this.

**Comment by jeremycherfas** [comment]
Fixed, but may be fragile.

**Comment by arslanthere** [comment]
https://www.ted.com/profiles/27212663
--
https://en.gravatar.com/arslanthere
https://www.hotfrog.com/company/1454646228758528
https://www.merchantcircle.com/immigration-consultants-singapore-bellevue-ky
https://www.2findlocal.com/b/13881580/immigration-consultants-singapore-singapore-singapore?
https://www.spoke.com/companies/immigration-consultants-singapore-60684a9b2cd3fa3dbb05c7fe
https://us.enrollbusiness.com/BusinessProfile/5376858/Immigration%20Consultants%20Singapore
https://www.salespider.com/p-23259434/arslan-hyder
https://www.pennysaverusa.com/user/profile/1816109
https://www.tuugo.us/userProfile/arslanhyder2019/2391088
http://www.linkbyme.com/panel1/
https://sg.zipleaf.com/Companies/Immigration-Consultants-Singapore
https://www.igotbiz.com/directory/listingdisplay.aspx?lid=65346
https://oh-cincinnati.cataloxy.us/firms/immigration.sg.htm
https://forms.americantowns.com/viewevent/66776999
https://forms.americantowns.com/viewgroup/2037270
https://www.finduslocal.com/local-business/california/fresno/marce-d-furtado-wholesale_4504-north-valentine-avenue-apartment-105/
https://www.bizcommunity.com/Company/ImmigrationConsultantsSingapore
https://www.cybo.com/SG-biz/one-commonwealth_20
https://www.callupcontact.com/b/businessprofile/Immigration_Consultants_Singapore/7692194
https://about.me/arslanhyder/getstarted
https://ebusinesspages.com/arslanthere.user
https://www.instructables.com/member/arslanthere/?cb=1617628188
https://www.n49.com/biz/4284608/immigration-consultants-oh-cincinnati-01-one-commonwealth-building-1-commonwealth-lane/
https://www.storeboard.com/immigrationconsultantssingapore
https://www.techinasia.com/companies/immigration-consultants?is_created
https://www.worldbid.com/travel-sports-recreation/tours-travel/immigration-consultants-i324519.html
https://citysquares.com/listings/24264274/upgrade
https://www.mywot.com/user/8591427/sites/
https://www.golocal247.com/user/dashboard#profile
